# Generated by Django 6.1 on 2026-09-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tag_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
