# Generated by Django 6.1 on 2026-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_line_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='line_link_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
