# Generated by Django 6.1 on 2026-08-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyTask',
        ),
    ]
