# Generated by Django 6.1 on 2026-09-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_todo', '0002_delete_monthlytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylist',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
