# Generated by Django 6.0.7 on 2026-07-31 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneDayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OneDayTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('one_day_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='OneDay_todo.onedaylist')),
            ],
        ),
    ]
