# Generated by Django 6.0.7 on 2026-08-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneDay_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaytask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
