# Generated by Django 6.1 on 2026-09-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoalShare', '0003_alter_dailyreflection_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreflection',
            old_name='completed_tasks_snapshot',
            new_name='selected_tasks',
        ),
    ]
